# Generated by Django 5.0.2 on 2024-02-24 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dream_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list_of_dream',
            name='dream',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='steps_to_concretize',
            name='description',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
