# Generated by Django 5.0.2 on 2024-02-26 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dream_list', '0003_steps_to_concretize_dream'),
    ]

    operations = [
        migrations.AddField(
            model_name='list_of_dream',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='steps_to_concretize',
            name='step_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='list_of_dream',
            name='schedule',
            field=models.DurationField(default=0),
        ),
    ]
